// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1gmCTuYEiQ6KXyBCt2puBTOZ8ihQh2KU',
    appId: '1:120323885544:web:980e7c9ea8a3bb3482fc5d',
    messagingSenderId: '120323885544',
    projectId: 'nexserv-6d881',
    authDomain: 'nexserv-6d881.firebaseapp.com',
    storageBucket: 'nexserv-6d881.firebasestorage.app',
    measurementId: 'G-TFKMDNZ983',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjndOo0SwrbJl2avT2RZzs-XNffmwFvVI',
    appId: '1:120323885544:android:82af65765aa3caf882fc5d',
    messagingSenderId: '120323885544',
    projectId: 'nexserv-6d881',
    storageBucket: 'nexserv-6d881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDptJJvoQNj5vA0ta3k_HTvQSeqo2i-GVM',
    appId: '1:120323885544:ios:96d3f10a79ecf80d82fc5d',
    messagingSenderId: '120323885544',
    projectId: 'nexserv-6d881',
    storageBucket: 'nexserv-6d881.firebasestorage.app',
    iosBundleId: 'com.example.coopGigApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDptJJvoQNj5vA0ta3k_HTvQSeqo2i-GVM',
    appId: '1:120323885544:ios:96d3f10a79ecf80d82fc5d',
    messagingSenderId: '120323885544',
    projectId: 'nexserv-6d881',
    storageBucket: 'nexserv-6d881.firebasestorage.app',
    iosBundleId: 'com.example.coopGigApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1gmCTuYEiQ6KXyBCt2puBTOZ8ihQh2KU',
    appId: '1:120323885544:web:b42b2dbe54ed912e82fc5d',
    messagingSenderId: '120323885544',
    projectId: 'nexserv-6d881',
    authDomain: 'nexserv-6d881.firebaseapp.com',
    storageBucket: 'nexserv-6d881.firebasestorage.app',
    measurementId: 'G-WXY1F19JLE',
  );
}
